/* Generated By:JavaCC: Do not edit this line. FuckCTreeConstants.java Version 5.0 */
package pkg;

public interface FuckCTreeConstants
{
  public int JJTSTART = 0;
  public int JJTTOP_UNIT = 1;
  public int JJTEX_DECL = 2;
  public int JJTFUN_DEF = 3;
  public int JJTPARAM_TYPE_LIST = 4;
  public int JJTPARAM_LIST = 5;
  public int JJTPARAM_DECL = 6;
  public int JJTCOMPOUND_STM = 7;
  public int JJTSTMT_LIST = 8;
  public int JJTSTMT = 9;
  public int JJTIF_SWITCH_STMT = 10;
  public int JJTCASE_DEFAULT_STMT = 11;
  public int JJTWHILE_FOR_STMT = 12;
  public int JJTJUMP_STMT = 13;
  public int JJTCONSTANT_EXPR = 14;
  public int JJTEXPR_STMT = 15;
  public int JJTEXPR = 16;
  public int JJTDECL_LIST = 17;
  public int JJTDECLS = 18;
  public int JJTDECL_SPECIFIERS = 19;
  public int JJTSTORAGE_SPECIFIERS = 20;
  public int JJTTYPE_MODIFIERS = 21;
  public int JJTTYPE_SPECIFIERS = 22;
  public int JJTTYPE_QUALIFIERS = 23;
  public int JJTINIT_DECL_LIST = 24;
  public int JJTINIT_DECL = 25;
  public int JJTDECL = 26;
  public int JJTDIRECT_DECL = 27;
  public int JJTPTR = 28;
  public int JJTINIT = 29;
  public int JJTINIT_LIST = 30;
  public int JJTASSIGN_EXPR = 31;
  public int JJTASSIGN_OPERATOR = 32;
  public int JJTUNARY_EXPR = 33;
  public int JJTPOSTFIX_EXPR = 34;
  public int JJTPREFIX_EXPR = 35;
  public int JJTCOND_EXPR = 36;
  public int JJTLOGICAL_OR_EXPR = 37;
  public int JJTLOGICAL_AND_EXPR = 38;
  public int JJTINCLUSIVE_OR_EXPR = 39;
  public int JJTEXCLUSIVE_OR_EXPR = 40;
  public int JJTAND_EXPR = 41;
  public int JJTEQUAL_EXPR = 42;
  public int JJTRELATION_EXPR = 43;
  public int JJTSHIFT_EXPR = 44;
  public int JJTADDITIVE_EXPR = 45;
  public int JJTMULTIPLICATIVE_EXPR = 46;
  public int JJTCONSTANT = 47;


  public String[] jjtNodeName = {
    "Start",
    "top_unit",
    "ex_decl",
    "fun_def",
    "param_type_list",
    "param_list",
    "param_decl",
    "compound_stm",
    "stmt_list",
    "stmt",
    "if_switch_stmt",
    "case_default_stmt",
    "while_for_stmt",
    "jump_stmt",
    "constant_expr",
    "expr_stmt",
    "expr",
    "decl_list",
    "decls",
    "decl_specifiers",
    "storage_specifiers",
    "type_modifiers",
    "type_specifiers",
    "type_qualifiers",
    "init_decl_list",
    "init_decl",
    "decl",
    "direct_decl",
    "ptr",
    "init",
    "init_list",
    "assign_expr",
    "assign_operator",
    "unary_expr",
    "postfix_expr",
    "prefix_expr",
    "cond_expr",
    "logical_or_expr",
    "logical_and_expr",
    "Inclusive_or_expr",
    "exclusive_or_expr",
    "and_expr",
    "equal_expr",
    "relation_expr",
    "shift_expr",
    "additive_expr",
    "multiplicative_expr",
    "constant",
  };
}
/* JavaCC - OriginalChecksum=d744083f2e3ec943de021a91540caa47 (do not edit this line) */
