/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package net.loveruby.cflat.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SPACES = 1;
  /** RegularExpression Id. */
  int BLOCK_COMMENT = 4;
  /** RegularExpression Id. */
  int LINE_COMMENT = 5;
  /** RegularExpression Id. */
  int VOID = 6;
  /** RegularExpression Id. */
  int CHAR = 7;
  /** RegularExpression Id. */
  int SHORT = 8;
  /** RegularExpression Id. */
  int INT = 9;
  /** RegularExpression Id. */
  int LONG = 10;
  /** RegularExpression Id. */
  int STRUCT = 11;
  /** RegularExpression Id. */
  int ENUM = 12;
  /** RegularExpression Id. */
  int STATIC = 13;
  /** RegularExpression Id. */
  int CONST = 14;
  /** RegularExpression Id. */
  int SIGNED = 15;
  /** RegularExpression Id. */
  int UNSIGNED = 16;
  /** RegularExpression Id. */
  int IF = 17;
  /** RegularExpression Id. */
  int ELSE = 18;
  /** RegularExpression Id. */
  int DEFAULT_ = 19;
  /** RegularExpression Id. */
  int WHILE = 20;
  /** RegularExpression Id. */
  int DO = 21;
  /** RegularExpression Id. */
  int FOR = 22;
  /** RegularExpression Id. */
  int RETURN = 23;
  /** RegularExpression Id. */
  int BREAK = 24;
  /** RegularExpression Id. */
  int CONTINUE = 25;
  /** RegularExpression Id. */
  int SIZEOF = 26;
  /** RegularExpression Id. */
  int IDENTIFIER = 27;
  /** RegularExpression Id. */
  int INTEGER = 28;
  /** RegularExpression Id. */
  int REAL_NUMBER = 29;
  /** RegularExpression Id. */
  int EXPONENT = 30;
  /** RegularExpression Id. */
  int CHARACTER = 35;
  /** RegularExpression Id. */
  int STRING = 40;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_BLOCK_COMMENT = 1;
  /** Lexical state. */
  int IN_CHARACTER = 2;
  /** Lexical state. */
  int CHARACTER_TERM = 3;
  /** Lexical state. */
  int IN_STRING = 4;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<SPACES>",
    "\"/*\"",
    "<token of kind 3>",
    "\"*/\"",
    "<LINE_COMMENT>",
    "\"void\"",
    "\"char\"",
    "\"short\"",
    "\"int\"",
    "\"long\"",
    "\"struct\"",
    "\"enum\"",
    "\"static\"",
    "\"const\"",
    "\"signed\"",
    "\"unsigned\"",
    "\"if\"",
    "\"else\"",
    "\"default\"",
    "\"while\"",
    "\"do\"",
    "\"for\"",
    "\"return\"",
    "\"break\"",
    "\"continue\"",
    "\"sizeof\"",
    "<IDENTIFIER>",
    "<INTEGER>",
    "<REAL_NUMBER>",
    "<EXPONENT>",
    "\"\\\'\"",
    "<token of kind 32>",
    "<token of kind 33>",
    "<token of kind 34>",
    "\"\\\'\"",
    "\"\\\"\"",
    "<token of kind 37>",
    "<token of kind 38>",
    "<token of kind 39>",
    "\"\\\"\"",
    "\"(\"",
    "\"=\"",
    "\",\"",
    "\";\"",
    "\")\"",
    "\"...\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"*\"",
    "\":\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"%=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"<<=\"",
    "\">>=\"",
    "\"?\"",
    "\"||\"",
    "\"&&\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"==\"",
    "\"!=\"",
    "\"|\"",
    "\"^\"",
    "\"&\"",
    "\">>\"",
    "\"<<\"",
    "\"+\"",
    "\"-\"",
    "\"/\"",
    "\"%\"",
    "\"++\"",
    "\"--\"",
    "\"!\"",
    "\"~\"",
    "\".\"",
    "\"->\"",
  };

}
